# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sequel-rails}
  s.version = "0.1.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brasten Sager (brasten)"]
  s.date = %q{2011-03-31}
  s.description = %q{Integrate Sequel with Rails 3}
  s.email = %q{brasten@gmail.com}
  s.extra_rdoc_files = [
    "CHANGELOG",
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CHANGELOG",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "lib/generators/sequel.rb",
    "lib/generators/sequel/migration/migration_generator.rb",
    "lib/generators/sequel/migration/templates/migration.rb",
    "lib/generators/sequel/model/model_generator.rb",
    "lib/generators/sequel/model/templates/model.rb",
    "lib/generators/sequel/observer/observer_generator.rb",
    "lib/generators/sequel/observer/templates/observer.rb",
    "lib/sequel-rails.rb",
    "lib/sequel-rails/configuration.rb",
    "lib/sequel-rails/migrations.rb",
    "lib/sequel-rails/railtie.rb",
    "lib/sequel-rails/railties/benchmarking_mixin.rb",
    "lib/sequel-rails/railties/controller_runtime.rb",
    "lib/sequel-rails/railties/database.rake",
    "lib/sequel-rails/railties/i18n_support.rb",
    "lib/sequel-rails/railties/log_subscriber.rb",
    "lib/sequel-rails/runtime.rb",
    "lib/sequel-rails/session_store.rb",
    "lib/sequel-rails/setup.rb",
    "lib/sequel-rails/storage.rb",
    "sequel-rails.gemspec",
    "spec/rcov.opts",
    "spec/setup_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/ci.rake",
    "tasks/clean.rake",
    "tasks/metrics.rake",
    "tasks/spec.rake",
    "tasks/yard.rake",
    "tasks/yardstick.rake"
  ]
  s.homepage = %q{http://github.com/brasten/sequel-rails}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Use Sequel with Rails 3}
  s.test_files = [
    "spec/setup_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_runtime_dependency(%q<yard>, ["~> 0.5"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<railties>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<sequel>, ["~> 3.13"])
      s.add_runtime_dependency(%q<sequel>, ["~> 3.13"])
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<railties>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.4"])
      s.add_dependency(%q<yard>, ["~> 0.5"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
      s.add_dependency(%q<railties>, ["~> 3.0.0"])
      s.add_dependency(%q<sequel>, ["~> 3.13"])
      s.add_dependency(%q<sequel>, ["~> 3.13"])
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
      s.add_dependency(%q<railties>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.4"])
    s.add_dependency(%q<yard>, ["~> 0.5"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
    s.add_dependency(%q<railties>, ["~> 3.0.0"])
    s.add_dependency(%q<sequel>, ["~> 3.13"])
    s.add_dependency(%q<sequel>, ["~> 3.13"])
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
    s.add_dependency(%q<railties>, ["~> 3.0.0"])
  end
end

